# Deploy Task for py-django-crewai
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
  - name: source-code
  - name: build-artifacts

outputs:
  - name: app-to-deploy

run:
  path: bash
  args:
    - -c
    - |
      # Extract artifacts
      mkdir -p app-to-deploy
      tar -xzf build-artifacts/artifacts.tar.gz -C app-to-deploy
      cd app-to-deploy
      unzip py-django-crewai.zip -d py-django-crewai

      # Copy manifest and any other required files
      cp -f ../source-code/py-django-crewai/manifest.yml py-django-crewai/
      cp -f ../source-code/py-django-crewai/Procfile py-django-crewai/ || echo "Procfile not found"
      cp -f ../source-code/py-django-crewai/runtime.txt py-django-crewai/ || echo "runtime.txt not found"

params:
  CF_API: ((cf_api))
  CF_USERNAME: ((cf_username))
  CF_PASSWORD: ((cf_password))
  CF_ORG: ((cf_org))
  CF_SPACE: ((cf_space))
  DJANGO_SETTINGS_MODULE: movie_chatbot.settings
  OPENAI_API_KEY: ((openai_api_key))
  DJANGO_SECRET_KEY: ((django_secret_key))
