# Deploy Task for js-langchain-react
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
  - name: source-code
  - name: build-artifacts

outputs:
  - name: app-to-deploy

run:
  path: bash
  args:
    - -c
    - |
      # Extract artifacts
      mkdir -p app-to-deploy
      tar -xzf build-artifacts/artifacts.tar.gz -C app-to-deploy

      # Copy manifest and any other required files
      cp source-code/js-langchain-react/manifest.yml app-to-deploy/
      cp source-code/js-langchain-react/server.js app-to-deploy/
      cp source-code/js-langchain-react/package.json app-to-deploy/

params:
  CF_API: ((cf_api))
  CF_USERNAME: ((cf_username))
  CF_PASSWORD: ((cf_password))
  CF_ORG: ((cf_org))
  CF_SPACE: ((cf_space))
  OPENAI_API_KEY: ((openai_api_key))
