# Dependabot configuration for multi-tech-stack repository
# This configuration keeps all dependencies up to date across all projects

version: 2
updates:
  # .NET projects - dotnet-extensions-ai
  - package-ecosystem: "nuget"
    directory: "/dotnet-extensions-ai"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dotnet"

  # Go projects - go-fiber-langchaingo
  - package-ecosystem: "gomod"
    directory: "/go-fiber-langchaingo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"

  # Java/Maven projects - java-spring-ai-mcp
  - package-ecosystem: "maven"
    directory: "/java-spring-ai-mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "java"

  # Java/Maven projects - java-spring-langgraph-mcp-angular backend
  - package-ecosystem: "maven"
    directory: "/java-spring-langgraph-mcp-angular"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "java"

  # Angular/npm frontend - java-spring-langgraph-mcp-angular
  - package-ecosystem: "npm"
    directory: "/java-spring-langgraph-mcp-angular/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "angular"
    ignore:
      # Ignore major version updates for Angular to avoid breaking changes
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]

  # Node.js/React project - js-langchain-react
  - package-ecosystem: "npm"
    directory: "/js-langchain-react"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "react"
    ignore:
      # Ignore major version updates for React to avoid breaking changes
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # PHP/Composer project - php-symfony-neuron
  - package-ecosystem: "composer"
    directory: "/php-symfony-neuron"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "php"
      - "symfony"
    ignore:
      # Ignore major version updates for Symfony to maintain stability
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]

  # Python/pip project - py-django-crewai
  - package-ecosystem: "pip"
    directory: "/py-django-crewai"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "django"
    ignore:
      # Ignore major version updates for Django to avoid breaking changes
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]

  # Python Django frontend - py-django-crewai
  - package-ecosystem: "npm"
    directory: "/py-django-crewai/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"

  # Ruby/Bundler project - ruby-sinatra-fastmcp
  - package-ecosystem: "bundler"
    directory: "/ruby-sinatra-fastmcp"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ruby"
      - "sinatra"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"