parameters:
    # General services
    rapid_api.api_key: '%env(resolve:RAPID_API_KEY)%'

    # GenAI/LLM Integration
    genai.api_key: '%env(resolve:GENAI_API_KEY)%'
    genai.base_url: '%env(resolve:GENAI_BASE_URL)%'
    genai.model: '%env(resolve:GENAI_MODEL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Yahoo Finance API Configuration
    App\Service\ApiClient\YahooFinanceClient:
        arguments:
            $params: '@parameter_bag'

    # Yahoo Finance API Service using the client
    App\Service\YahooFinanceService:
        arguments:
            $rapidApiKey: '%rapid_api.api_key%'
            $useMockData: '%env(default::bool:USE_MOCK_DATA)%'

    # Stock Clients Factory Configuration
    App\Service\ApiClient\StockClientsFactory:
        arguments:
            $useMockData: '%env(default::bool:USE_MOCK_DATA)%'
            
    # SEC API Client Factory Configuration
    App\Service\ApiClient\SecApiClientFactory:
        arguments:
            $useMockData: '%env(default::bool:USE_MOCK_DATA)%'

    # LLM Client Factory Configuration
    App\Service\LlmClientFactory:
        arguments:
            $apiKey: '%genai.api_key%'
            $baseUrl: '%genai.base_url%'
            $model: '%genai.model%'

    # Neuron AI Service Configuration
    App\Service\NeuronAiService:
        arguments:
            $clientFactory: '@App\Service\LlmClientFactory'
