# FILE: php-symfony-neuron/config/services.yaml
# Purpose: Defines application services and default configurations.

parameters:
    llm.api_key: '%env(GENAI_API_KEY)%'
    llm.base_url: '%env(GENAI_BASE_URL)%'
    llm.model: '%env(GENAI_MODEL)%'
    env(USE_MOCK_DATA): '%env(bool:USE_MOCK_DATA)%'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies
        autoconfigure: true # Automatically registers services
        bind:
            Psr\Log\LoggerInterface: '@logger'
            # API keys are best bound in package configs or injected via constructor args

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            # Exclude API client implementations AND factories - we define them explicitly
            - '../src/Service/ApiClient/'

    # --- Define ALL Concrete Implementations (Real & Mock) ---
    # These need to be defined so the factories can locate them.
    App\Service\ApiClient\AlphaVantageClient: ~ # ~ uses _defaults
    App\Service\ApiClient\YahooFinanceClient: ~
    App\Service\ApiClient\SecApiClient: ~
    App\Service\ApiClient\NewsApiClient: ~
    App\Service\ApiClient\EdgarApiClient: ~
    App\Service\ApiClient\LinkedInApiClient: ~

    App\Service\ApiClient\MockAlphaVantageClient: ~
    App\Service\ApiClient\MockYahooFinanceClient: ~
    App\Service\ApiClient\MockSecApiClient: ~
    App\Service\ApiClient\MockNewsApiClient: ~
    App\Service\ApiClient\MockEdgarApiClient: ~
    App\Service\ApiClient\MockLinkedInApiClient: ~

    # --- Define the Factories ---
    # We use a service locator for the factories to avoid circular dependencies
    # and allow the factories to access the correct client service.
    App\Service\ApiClient\EdgarClientFactory:
        arguments:
            $locator: !service_locator # Use a service locator
                # List the services this factory needs access to
                - App\Service\ApiClient\EdgarApiClient
                - App\Service\ApiClient\MockEdgarApiClient
            $useMockData: '%env(bool:USE_MOCK_DATA)%'
        tags: ['container.service_subscriber'] # Tag for service locator

    App\Service\ApiClient\LinkedInClientFactory:
        arguments:
            $locator: !service_locator
                # List the services this factory needs access to
                - App\Service\ApiClient\LinkedInApiClient
                - App\Service\ApiClient\MockLinkedInApiClient
            $useMockData: '%env(bool:USE_MOCK_DATA)%'
        tags: ['container.service_subscriber']

    App\Service\ApiClient\StockClientsFactory:
         arguments:
            $locator: !service_locator
                # List the services this factory needs access to
                - App\Service\ApiClient\AlphaVantageClient
                - App\Service\ApiClient\MockAlphaVantageClient
                - App\Service\ApiClient\YahooFinanceClient
                - App\Service\ApiClient\MockYahooFinanceClient
                - App\Service\ApiClient\NewsApiClient
                - App\Service\ApiClient\MockNewsApiClient
                - App\Service\ApiClient\SecApiClient
                - App\Service\ApiClient\MockSecApiClient
            $useMockData: '%env(bool:USE_MOCK_DATA)%'
         tags: ['container.service_subscriber']

    # --- Service Definitions that USE the API Clients ---
    # Inject the FACTORIES now, not the clients directly.

    App\Service\StockDataService:
        arguments:
            # Inject the factory
            $stockClientsFactory: '@App\Service\ApiClient\StockClientsFactory'
            # Other dependencies (autowired or explicit)
            $entityManager: '@doctrine.orm.entity_manager'
            $cache: '@stock_data.cache' # Ensure stock_data.cache is defined (e.g., in stock_api.yaml)
            $logger: '@logger'
        # No longer injecting individual clients here

    App\Service\SecFilingService:
        arguments:
            # Inject the factory
            $edgarClientFactory: '@App\Service\ApiClient\EdgarClientFactory'
            # Other dependencies... (autowired or explicit)
            $neuronAiService: '@App\Service\NeuronAiService'
            $entityManager: '@doctrine.orm.entity_manager'
            $secFilingRepository: '@App\Repository\SecFilingRepository'
            $logger: '@logger'
        # No longer injecting $edgarApiClient here

    App\Service\LinkedInService:
        arguments:
            # Inject the factory
            $linkedInClientFactory: '@App\Service\ApiClient\LinkedInClientFactory'
            # Other dependencies... (autowired or explicit)
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@logger'
            $requestStack: '@request_stack'
        # No longer injecting $linkedInApiClient here

    # --- Other Services ---
    App\Service\LlmClientFactory:
        arguments:
            $apiKey: '%llm.api_key%'
            $baseUrl: '%llm.base_url%'
            $model: '%llm.model%'

    App\Service\NeuronAiService:
        arguments:
            $clientFactory: '@App\Service\LlmClientFactory'

    App\Service\ReportExportService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Cache definition should remain in stock_api.yaml or cache.yaml
