# Build Frontend Task for java-spring-langgraph-mcp-angular
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '18'

inputs:
  - name: source-code

outputs:
  - name: frontend-build

run:
  path: bash
  args:
    - -c
    - |
      cd source-code/java-spring-langgraph-mcp-angular/frontend

      # Install dependencies
      echo "Installing frontend dependencies..."
      npm install

      # Build frontend
      echo "Building frontend..."
      npm run build -- --configuration production

      # Copy build to output
      echo "Copying frontend artifacts..."
      mkdir -p ../../../frontend-build
      cp -r dist ../../../frontend-build/
