# Build Backend Task for java-spring-langgraph-mcp-angular
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.9-eclipse-temurin-17'

inputs:
  - name: source-code

outputs:
  - name: backend-build

run:
  path: bash
  args:
    - -c
    - |
      cd source-code/java-spring-langgraph-mcp-angular

      # Build backend with Maven
      echo "Building backend with Maven..."
      mvn -B clean package -f backend/pom.xml

      # Copy JAR to output
      echo "Copying backend artifacts..."
      mkdir -p ../../backend-build
      cp backend/target/*.jar ../../backend-build/
