# Deploy Task for ruby-sinatra-fastmcp
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
  - name: source-code
  - name: build-artifacts

outputs:
  - name: app-to-deploy

run:
  path: bash
  args:
    - -c
    - |
      # Extract artifacts
      mkdir -p app-to-deploy
      tar -xzf build-artifacts/artifacts.tar.gz -C app-to-deploy
      cd app-to-deploy
      unzip ruby-sinatra-fastmcp.zip -d ruby-sinatra-fastmcp

      # Copy manifest and any other required files
      cp -f ../source-code/ruby-sinatra-fastmcp/manifest.yml ruby-sinatra-fastmcp/
      cp -f ../source-code/ruby-sinatra-fastmcp/Procfile ruby-sinatra-fastmcp/ || echo "Procfile not found"

params:
  CF_API: ((cf_api))
  CF_USERNAME: ((cf_username))
  CF_PASSWORD: ((cf_password))
  CF_ORG: ((cf_org))
  CF_SPACE: ((cf_space))
  RACK_ENV: production
  OPENAI_API_KEY: ((openai_api_key))
