# FILE: php-symfony-neuron/config/packages/edgar_api.yaml
# Purpose: Configuration for the SEC EDGAR API integration

parameters:
    # User-Agent header for SEC EDGAR API requests
    # This should follow SEC guidelines: organization name and email
    # See: https://www.sec.gov/os/webmaster-faq#code-of-conduct
    edgar_api.user_agent: 'Research Application (research@company.com)'

    # These environment variables can be overridden in .env.local
    # We don't need an API key for the SEC EDGAR API - only a proper User-Agent header

services:
    # Add any specific services needed for the EDGAR API here

    # Note: The ApiClient\EdgarClientFactory and related services are
    # defined in config/services.yaml for consistency with other API clients
