framework:
    secret: '%env(APP_SECRET)%'

<<<<<<< ours
    # Enables session support
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
=======
    # Note that the session will be started ONLY if you read or write from it.
    session: true
>>>>>>> theirs

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
