framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Enable HTTP Client with proper configuration
    http_client:
        default_options:
            headers:
                'User-Agent': 'Symfony/NeuronAI Financial Research Application'
        # We don't need any scoped clients - just use the default http_client

    # Enabled the trusted proxies
    # trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    # trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    # Enabled the trusted hosts
    # trusted_hosts: ~

    # Set a session cookie secure if you are accessing app via https
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
