# FILE: php-symfony-neuron/config/packages/linkedin_api.yaml
# Purpose: Defines configuration specific to the LinkedIn API client.

parameters:
    linkedin_api.client_id: '%env(resolve:LINKEDIN_CLIENT_ID)%'
    linkedin_api.client_secret: '%env(resolve:LINKEDIN_CLIENT_SECRET)%'
    linkedin_api.redirect_uri: '%env(resolve:LINKEDIN_REDIRECT_URI)%'

services:
    # Configure the LinkedIn API client
    # Rely on autowiring for $params, $logger, and $requestStack
    # Ensure these services are available/autowirable in your container
    App\Service\ApiClient\LinkedInApiClient: ~
        # arguments: # Removed explicit arguments, relying on autowiring
            # $params: '@parameter_bag' # Usually autowirable
            # $logger: '@logger'       # Usually autowirable
            # $requestStack: '@request_stack' # Usually autowirable