parameters:
    # Stock and financial APIs
    alpha_vantage.api_key: '%env(resolve:ALPHA_VANTAGE_API_KEY)%'
    yahoo_finance.api_key: '%env(resolve:RAPID_API_KEY)%'
    news_api.api_key: '%env(resolve:NEWS_API_KEY)%'
    kaleidoscope_api.key: '%env(resolve:KALEIDOSCOPE_API_KEY)%'
    kaleidoscope_api.base_url_default: 'https://api.kscope.io/v2'
    kaleidoscope_api.base_url: '%env(default:kaleidoscope_api.base_url_default:KALEIDOSCOPE_BASE_URL)%'

services:
    # Configure cache for the stock data service
    stock_data.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            $namespace: 'stock_data'
            $defaultLifetime: 3600
            $directory: '%kernel.cache_dir%/stock_data'

    # API clients - removed explicit service definition since we're using factories now

    # Stock data cache definition only
    # The StockDataService is now defined in services.yaml using the factory pattern
