# Deploy Server Task for java-spring-ai-mcp
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
  - name: source-code
  - name: build-artifacts

outputs:
  - name: app-to-deploy

run:
  path: bash
  args:
    - -c
    - |
      # Extract artifacts
      mkdir -p app-to-deploy
      tar -xzf build-artifacts/artifacts.tar.gz -C app-to-deploy

      # Copy manifest
      cp source-code/java-spring-ai-mcp/server/manifest.yml app-to-deploy/

      # Find the server JAR
      SERVER_JAR=$(find app-to-deploy -name "*server*.jar" | head -1)
      if [ -z "$SERVER_JAR" ]; then
        echo "Server JAR not found!"
        exit 1
      fi

      # Rename to app.jar for Cloud Foundry
      cp "$SERVER_JAR" app-to-deploy/app.jar

params:
  CF_API: ((cf_api))
  CF_USERNAME: ((cf_username))
  CF_PASSWORD: ((cf_password))
  CF_ORG: ((cf_org))
  CF_SPACE: ((cf_space))
  SPRING_PROFILES_ACTIVE: cloud
  OPENAI_API_KEY: ((openai_api_key))
