# BitBucket Pipelines for js-langchain-react
# Equivalent to GitHub Actions workflow: js-langchain-react.yml

image: node:22

definitions:
  caches:
    npm: ~/.npm

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - npm
        script:
          - cd js-langchain-react
          - npm install
          - npm run build
          - npm test || echo "No tests specified"
        artifacts:
          - js-langchain-react/build/**

  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - npm
          script:
            - cd js-langchain-react
            - npm install
            - npm run build
            - npm test || echo "No tests specified"
          artifacts:
            - js-langchain-react/build/**
      - step:
          name: Upload Artifacts
          script:
            - cd js-langchain-react
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: 'build.tar.gz'
                TARGET: 'artifacts/js-langchain-react-${BITBUCKET_BUILD_NUMBER}.tar.gz'
            - echo "Creating archive of build files"
            - tar -czf build.tar.gz build/
      - step:
          name: Deploy to Cloud Foundry
          deployment: production
          trigger: manual
          script:
            - apt-get update && apt-get install -y wget gnupg2 apt-transport-https
            - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
            - echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            - apt-get update && apt-get install -y cf8-cli jq
            - cd js-langchain-react
            - echo "Deploying to Cloud Foundry..."
            - cf api $CF_API
            - cf auth $CF_USERNAME $CF_PASSWORD
            - cf target -o $CF_ORG -s $CF_SPACE

            # Create GenAI service if it doesn't exist
            - |
              if ! cf service news-aggregator-llm > /dev/null 2>&1; then
                echo "Creating GenAI service..."
                cf create-service genai standard news-aggregator-llm || echo "Service creation failed, it might already exist or plan is not available"
              else
                echo "GenAI service already exists"
              fi

            # Set environment variables
            - |
              APP_NAME=$(grep 'name:' manifest.yml | head -n 1 | awk '{print $2}')
              if [ -z "$APP_NAME" ]; then
                APP_NAME=$(basename $(pwd)) # Fallback to directory name
              fi

              # Push the application without starting it
              if [ "$RANDOM_ROUTE" = "true" ]; then
                echo "Pushing with random route..."
                cf push "$APP_NAME" -f manifest.yml --no-start --random-route
              else
                echo "Pushing with route from manifest..."
                cf push "$APP_NAME" -f manifest.yml --no-start
              fi

              # Set environment variables
              if [ -n "$NEWS_API_KEY" ]; then
                cf set-env "$APP_NAME" "NEWS_API_KEY" "$NEWS_API_KEY"
              fi

              if [ -n "$LLM_API_KEY" ]; then
                cf set-env "$APP_NAME" "API_KEY" "$LLM_API_KEY"
              fi

              # Start the application
              cf start "$APP_NAME"

clone:
  depth: full

options:
  max-time: 20

# Custom deployment variables
# These can be set in the Bitbucket repository settings
# CF_API: Cloud Foundry API endpoint
# CF_USERNAME: Cloud Foundry username
# CF_PASSWORD: Cloud Foundry password
# CF_ORG: Cloud Foundry organization
# CF_SPACE: Cloud Foundry space
# RANDOM_ROUTE: Whether to use a random route (true/false)
# NEWS_API_KEY: News API key
# LLM_API_KEY: LLM API key
