name: Deploy py-django-crewai to TP4CF

on:
  workflow_call:
    inputs:
      cf_api:
        required: true
        type: string
        description: 'Cloud Foundry API Endpoint'
      cf_username:
        required: false
        type: string
        description: 'Cloud Foundry Username (not required if using SSO)'
      use_sso:
        required: false
        type: boolean
        default: false
        description: 'Whether to use SSO authentication instead of username/password'
      cf_org:
        required: true
        type: string
        description: 'Cloud Foundry Target Organization'
      cf_space:
        required: true
        type: string
        description: 'Cloud Foundry Target Space'
      genai_plan:
        required: false
        type: string
        description: 'GenAI Service Plan Name (if needed by app)'
      db_service_type:
        required: false
        type: string
        default: 'postgresql'
        description: 'Database Service Type (e.g., postgresql, mysql)'
      db_plan:
        required: false
        type: string
        description: 'Database Service Plan Name'
    secrets:
      CF_PASSWORD:
        required: false
        description: 'Cloud Foundry Password (not required if using SSO)'
      CF_SSO_REFRESH_TOKEN:
        required: false
        description: 'Cloud Foundry SSO Refresh Token (not required if using username/password)'
      DJANGO_SECRET_KEY:
        required: false
        description: 'Django Secret Key'
      OPENAI_API_KEY:
        required: false
        description: 'OpenAI API Key'
      TMDB_API_KEY:
        required: false
        description: 'TMDB API Key'
      SERPAPI_API_KEY:
        required: false
        description: 'SerpAPI API Key'

jobs:
  build:
    uses: ./.github/workflows/py-django-crewai.yml

  authenticate:
    needs: build
    uses: ./.github/workflows/cf-auth.yml
    with:
      cf_api: ${{ inputs.cf_api }}
      cf_username: ${{ inputs.cf_username }}
      use_sso: ${{ inputs.use_sso }}
    secrets:
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_SSO_REFRESH_TOKEN: ${{ secrets.CF_SSO_REFRESH_TOKEN }}

  setup_org_space:
    needs: authenticate
    uses: ./.github/workflows/cf-org-space.yml
    with:
      cf_org: ${{ inputs.cf_org }}
      cf_space: ${{ inputs.cf_space }}

  create_services:
    needs: setup_org_space
    uses: ./.github/workflows/cf-create-services.yml
    with:
      genai_service_name: 'movie-chatbot-llm'
      genai_plan: ${{ inputs.genai_plan }}
      db_service_name: 'movie-chatbot-db'
      db_service_type: ${{ inputs.db_service_type }}
      db_plan: ${{ inputs.db_plan }}

  set_env_vars:
    needs: create_services
    runs-on: ubuntu-latest
    steps:
      - name: Create env vars file
        run: |
          echo '{
            "DJANGO_SECRET_KEY": "${{ secrets.DJANGO_SECRET_KEY }}",
            "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
            "TMDB_API_KEY": "${{ secrets.TMDB_API_KEY }}",
            "SERPAPI_API_KEY": "${{ secrets.SERPAPI_API_KEY }}"
          }' > env_vars.json
          cat env_vars.json
      - name: Upload env vars file
        uses: actions/upload-artifact@v4
        with:
          name: env-vars
          path: env_vars.json
          retention-days: 1

  deploy:
    needs: set_env_vars
    uses: ./.github/workflows/cf-deploy.yml
    with:
      project_path: 'py-django-crewai'
