name: java-spring-langgraph-mcp-angular CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - 'java-spring-langgraph-mcp-angular/**'
      - '.github/workflows/java-spring-langgraph-mcp-angular.yml'
  pull_request:
    paths:
      - 'java-spring-langgraph-mcp-angular/**'
      - '.github/workflows/java-spring-langgraph-mcp-angular.yml'

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-spring-langgraph-mcp-angular/backend

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'liberica'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build backend with Maven
      run: mvn -B package --file pom.xml

    - name: Upload backend artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v5
      with:
        name: java-spring-langgraph-mcp-angular-backend
        path: java-spring-langgraph-mcp-angular/backend/target/*.jar

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-spring-langgraph-mcp-angular/frontend

    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build -- --configuration production

    - name: Upload frontend artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v5
      with:
        name: java-spring-langgraph-mcp-angular-frontend
        path: java-spring-langgraph-mcp-angular/frontend/dist/
