name: js-langchain-react CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - 'js-langchain-react/**'
      - '.github/workflows/js-langchain-react.yml'
  pull_request:
    paths:
      - 'js-langchain-react/**'
      - '.github/workflows/js-langchain-react.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js-langchain-react

    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test || echo "No tests specified"

    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: js-langchain-react-artifacts
        path: js-langchain-react/build
