name: php-symfony-neuron CI

on:
  workflow_call:
  push:
    paths:
      - 'php-symfony-neuron/**'
      - '.github/workflows/php-symfony-neuron.yml'
  pull_request:
    paths:
      - 'php-symfony-neuron/**'
      - '.github/workflows/php-symfony-neuron.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: php-symfony-neuron

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, gd, curl, dom, exif, fileinfo, ftp, gettext, opcache, posix, simplexml, tokenizer, zip, calendar
        coverage: none
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          vendor/bin/phpunit
        else
          echo "No tests directory found, skipping tests"
        fi

    - name: Create package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p build
        composer dump-autoload --optimize --no-dev
        zip -r build/php-symfony-neuron.zip . -x ".git/*" "tests/*" ".env*" ".github/*" "build/*"

    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: php-symfony-neuron-artifacts
        path: php-symfony-neuron/build/
